name: Piranesi
main: brazil.piranesi.Piranesi
version: 1.0
api-version: 1.16
load: startup
commands:
  pdebug:
    description: Debug for Piranesi
    usage: /<command><args>
    aliases:
      - pdeb